version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "senha-db"
      POSTGRES_USER: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - /home/renatogroffe/Desenvolvimento/Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  teste-pgadmin-compose:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "pg-admin@email.com"
      PGADMIN_DEFAULT_PASSWORD: "senha-db"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge